<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <PlatformTarget>AnyCPU</PlatformTarget>
        <LangVersion>preview</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <DebugSymbols>false</DebugSymbols>
        <DebugType>none</DebugType>
        <Optimize>true</Optimize>
        <Configurations>Debug;Release</Configurations>
        <TargetFrameworks>netstandard2.0;net462;net6</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup Condition="'$(TargetFramework)'=='net462'">
        <PackageReference Include="System.Net.Http" Version="4.3.4"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../NativeMemory/NativeMemory.csproj"/>
    </ItemGroup>

</Project>