<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <PlatformTarget>AnyCPU</PlatformTarget>
        <LangVersion>preview</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <DebugSymbols>false</DebugSymbols>
        <DebugType>none</DebugType>
        <Optimize>true</Optimize>
        <Configurations>Debug;Release</Configurations>
        <TargetFrameworks>netstandard2.0;net462;net6</TargetFrameworks>
    </PropertyGroup>

    <PropertyGroup Condition="'$(TargetFramework)'=='netstandard2.0'">
        <DefineConstants>NETSTANDARD2_0</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition="'$(TargetFramework)'=='net462'">
        <DefineConstants>NET462</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition="'$(TargetFramework)'=='net6'">
        <DefineConstants>NET6</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../DearImGuiInjection/DearImGuiInjection.csproj"/>
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)'=='netstandard2.0' or '$(TargetFramework)'=='net462'">
        <PackageReference Include="BepInEx.Core" Version="5.4.21"/>

        <Reference Include="UnityEngine">
            <HintPath>..\libs\net35\UnityEngine.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="UnityEngine.UI">
            <HintPath>..\libs\net35\UnityEngine.UI.dll</HintPath>
            <Private>False</Private>
        </Reference>
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)'=='net6'">
        <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be*" PrivateAssets="all"/>

        <Reference Include="Il2Cppmscorlib">
            <HintPath>..\libs\$(TargetFramework)\Il2Cppmscorlib.dll</HintPath>
            <Private>False</Private>
        </Reference>

        <Reference Include="UnityEngine">
            <HintPath>..\libs\$(TargetFramework)\UnityEngine.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="UnityEngine.AudioModule">
            <HintPath>..\libs\$(TargetFramework)\UnityEngine.AudioModule.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="UnityEngine.CoreModule">
            <HintPath>..\libs\$(TargetFramework)\UnityEngine.CoreModule.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="UnityEngine.PhysicsModule">
            <HintPath>..\libs\$(TargetFramework)\UnityEngine.PhysicsModule.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="UnityEngine.TextRenderingModule">
            <HintPath>..\libs\$(TargetFramework)\UnityEngine.TextRenderingModule.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="UnityEngine.UI">
            <HintPath>..\libs\$(TargetFramework)\UnityEngine.UI.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="UnityEngine.UIModule">
            <HintPath>..\libs\$(TargetFramework)\UnityEngine.UIModule.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="UnityEngine.IMGUIModule">
            <HintPath>..\libs\$(TargetFramework)\UnityEngine.IMGUIModule.dll</HintPath>
            <Private>False</Private>
        </Reference>
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)'=='netstandard2.0' or '$(TargetFramework)'=='net6'">
        <Reference Include="ImGui.NET">
            <HintPath>../libs/netstandard2.0/ImGui.NET.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)'=='net462'">
        <Reference Include="ImGui.NET">
            <HintPath>../libs/$(TargetFramework)/ImGui.NET.dll</HintPath>
        </Reference>
    </ItemGroup>

</Project>
